name: "vprofile-IAC"

on:
  push:
    branches:
      - main
      - stage
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

# Credentials for deployment to AWS
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: eu-north-1

jobs:
  terraform:
    name: "Apply Terraform Code Changes"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to latest version

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Updated to latest version
        with:
          terraform_version: "~> 1.6.0"
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}"

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan (Debug)
        id: plan
        run: |
          export TF_LOG=DEBUG
          terraform plan -no-color -input=false -out=planfile
        continue-on-error: true  # Ensures the job continues if `terraform plan` fails

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'  # Updated conditional
        run: exit 1
